export const ADD_TODO = 'ADD_TODO';
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
export const TOGGLE_TODO = 'TOGGLE_TODO';
export const EDIT_TODO = 'EDIT_TODO';
export const SAVE_TODO = 'SAVE_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';
export const CLEAR_COMPLETED = 'CLEAR_COMPLETED';
export const MARK_ALL = 'MARK_ALL';

/*async actions*/
export const ADD_TODO_REQUEST='ADD_TODO_REQUEST';
export const ADD_TODO_SUCCESS='ADD_TODO_SUCCESS';
export const ADD_TODO_ERROR='ADD_TODO_ERROR';

export const MARK_ALL_REQUEST='MARK_ALL_REQUEST';
export const MARK_ALL_SUCCESS='MARK_ALL_SUCCESS';
export const MARK_ALL_ERROR='MARK_ALL_ERROR';

export const TOGGLE_TODO_REQUEST='TOGGLE_TODO_REQUEST';
export const TOGGLE_TODO_SUCCESS='TOGGLE_TODO_SUCCESS';
export const TOGGLE_TODO_ERROR='TOGGLE_TODO_ERROR';

export const SAVE_TODO_REQUEST='SAVE_TODO_REQUEST';
export const SAVE_TODO_SUCCESS='SAVE_TODO_SUCCESS';
export const SAVE_TODO_ERROR='SAVE_TODO_ERROR';

export const REMOVE_TODO_REQUEST='REMOVE_TODO_REQUEST';
export const REMOVE_TODO_SUCCESS='REMOVE_TODO_SUCCESS';
export const REMOVE_TODO_ERROR='REMOVE_TODO_ERROR';

export const CLEAR_COMPLETED_REQUEST='CLEAR_COMPLETED_REQUEST';
export const CLEAR_COMPLETED_SUCCESS='CLEAR_COMPLETED_SUCCESS';
export const CLEAR_COMPLETED_ERROR='CLEAR_COMPLETED_ERROR';
